# -*- mode: python ; coding: utf-8 -*-
import sys
from os.path import join, dirname, exists

root_dir = dirname(__file__)

a = Analysis(
    [join(root_dir, 'src-backend', '__main__.py')],
    pathex=[root_dir, join(root_dir, 'src-backend')],
    binaries=[],
    datas=[
        (join(root_dir, 'src-backend', 'app'), join('app')),
        (join(root_dir, 'bengali_ocr.db'), '.'),
        (join(root_dir, 'config.json'), '.'),
    ],
    hiddenimports=[
        'fastapi',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.middleware',
        'uvicorn.middleware.asgi2',
        'uvicorn.middleware.asgi3',
        'uvicorn.middleware.wsgi',
        'uvicorn.server',
        'pytesseract',
        'PIL',
        'cv2',
        'numpy',
        'docx',
        'pydantic',
        'pydantic_settings',
        'multipart',
        'starlette',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.routing',
        'starlette.schemas',
        'starlette.staticfiles',
        'starlette.datastructures',
        'starlette.concurrency',
        'starlette.convertors',
        'starlette.exceptions',
        'starlette.formparsers',
        'starlette.requests',
        'starlette.responses',
        'starlette.types',
        'starlette.websockets',
        'anyio',
        'sniffio',
        'httptools',
        'websockets',
        'yaml',
        'json',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'pandas',
        'Jinja2',
        'PIL.ImageTk',
        'PIL.ImageShow',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
